name: cellranger_vdj
description: Runs Cell Ranger VDJ to assemble and annotate VDJ sequences from Chromium single-cell RNA-seq data.
keywords:
  - single-cell
  - VDJ
  - 10x Genomics
tools:
  - cellranger:
      description: Cell Ranger by 10x Genomics is used for assembling and annotating VDJ sequences from single-cell RNA-seq data, providing insights into the adaptive immune response.
      homepage: https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/what-is-cell-ranger-vdj
      documentation: https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/using/tutorial-ov
      tool_dev_url: https://github.com/10XGenomics/cellranger
      licence: 10x Genomics EULA
input:
  - sample:
      type: string
      description: Unique identifier for the sample being processed.
  - reads:
      type: file
      description: Directory containing FastQ files preprocessed to meet the Cell Ranger requirements.
      pattern: "*.{fastq,fastq.gz}"
  - reference:
      type: directory
      description: Directory containing the reference data necessary for the VDJ analysis.
output:
  - outs:
      type: directory
      description: Directory containing all outputs from the Cell Ranger VDJ analysis, including assembled contigs and annotation files.
      pattern: "${sample}/outs/*"
  - versions:
      type: file
      description: File containing the versions of the Cell Ranger software and the reference used in the analysis.
      pattern: "versions.yml"
authors:
  - Andre Fonseca (@oandrefonseca)
maintainers:
  - Andre Fonseca (@oandrefonseca)
