name: seurat_merge
description: Merges multiple post-quality control Seurat objects into a single Seurat object for further analysis, incorporating sample metadata and normalizing data as needed. The process is documented through a comprehensive Quarto-rendered report.
keywords:
  - single-cell
  - Seurat
  - data merging
  - normalization
  - Quarto
tools:
  - quarto:
      description: Quarto is a scientific and technical publishing system built on Pandoc.
      homepage: https://quarto.org/
      documentation: https://quarto.org/docs/
      tool_dev_url: https://github.com/quarto-dev/quarto-cli
      licence: "GPL-3.0"
  - seurat:
      description: Seurat is an R package designed for QC, analysis, and exploration of single-cell RNA-seq data.
      homepage: https://satijalab.org/seurat/
      documentation: https://satijalab.org/seurat/articles/get_started.html
      tool_dev_url: https://github.com/satijalab/seurat
      licence: "GPL-3.0"
  - readr:
      description: readr is an R package to read text data quickly and efficiently.
      homepage: https://readr.tidyverse.org/
      documentation: https://readr.tidyverse.org/
      tool_dev_url: https://github.com/tidyverse/readr
  - dplyr:
      description: dplyr is an R package for data manipulation operations.
      homepage: https://dplyr.tidyverse.org/
      documentation: https://dplyr.tidyverse.org/
      tool_dev_url: https://github.com/tidyverse/dplyr
  - ggplot2:
      description: ggplot2 is an R package for creating complex visualizations.
      homepage: https://ggplot2.tidyverse.org/
      documentation: https://ggplot2.tidyverse.org/
      tool_dev_url: https://github.com/tidyverse/ggplot2
input:
  - qc_approved:
      type: file
      description: Files of approved Seurat objects post-quality control.
      pattern: "*.RDS"
  - notebook_merge:
      type: file
      description: Quarto notebook file (.qmd) used to merge the Seurat objects and perform initial data normalization.
      pattern: "*.qmd"
      parameters:
        project_name: 'Test'
        input_qc_approved: '/Users/affaustino/Projects/SCRATCH-QC/work/d6/2dde3a01223a736a5c2ff7ddb087ab/SRX5128504_seurat_object.RDS;/Users/affaustino/Projects/SCRATCH-QC/work/d6/2dde3a01223a736a5c2ff7ddb087ab/SRX5128478_seurat_object.RDS'
        input_exp_table: '/Users/affaustino/Projects/SCRATCH-QC/work/d6/2dde3a01223a736a5c2ff7ddb087ab/samplesheet.valid.csv'
        n_threads: 8
        n_memory: 16
  - exp_table:
      type: file
      description: CSV file containing the experimental metadata related to the samples.
      pattern: "*.csv"
  - page_config:
      type: file
      description: Configuration file that may contain additional settings or parameters for the notebook rendering.
      pattern: "*.{yml,yaml,json}"
output:
  - seurat_rds:
      type: file
      description: The merged and normalized Seurat RDS file containing single-cell RNA-seq data post-merge.
      pattern: "data/${params.project_name}_qc_merged_object.RDS"
  - html:
      type: file
      description: The rendered HTML report of the merging process summarized in the Quarto notebook.
      pattern: "report/${notebook_merge.baseName}.html"
authors:
  - Andre Fonseca (@oandrefonseca)
maintainers:
  - Andre Fonseca (@oandrefonseca)
